'use client';

import { useState } from 'react';
import styles from './PlanDisplay.module.css';
import ChecklistItem from './ChecklistItem';

export default function PlanDisplay({ plan, onReset, city }) {
  const [showToast, setShowToast] = useState(false);

  const handlePrint = () => {
    window.print();
  };

  const handleShare = async () => {
    const shareData = {
      title: 'MonsoonReady - My Preparedness Plan',
      text: `Check out my personalized monsoon preparedness plan for ${city}! Generated by MonsoonReady.`,
      url: window.location.href,
    };

    if (navigator.share) {
      try {
        await navigator.share(shareData);
      } catch (err) {
        if (err.name !== 'AbortError') {
          copyToClipboard();
        }
      }
    } else {
      copyToClipboard();
    }
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(window.location.href).then(() => {
      setShowToast(true);
      setTimeout(() => setShowToast(false), 2500);
    });
  };

  return (
    <section className={styles.planSection}>
      <div className={styles.planHeader}>
        <h2 className={styles.planTitle}>{plan.planTitle || 'Your Personalized Monsoon Plan'}</h2>
        <p className={styles.planSummary}>{plan.familySummary}</p>
      </div>

      <div className={`${styles.actions} no-print`}>
        <button
          className={`${styles.actionBtn} ${styles.primaryBtn}`}
          onClick={onReset}
          aria-label="Generate a new monsoon plan"
        >
          🔄 New Plan
        </button>
        <button
          className={`${styles.actionBtn} ${styles.secondaryBtn}`}
          onClick={handlePrint}
          aria-label="Download plan as PDF"
        >
          📄 Download PDF
        </button>
        <button
          className={`${styles.actionBtn} ${styles.secondaryBtn}`}
          onClick={handleShare}
          aria-label="Share your monsoon plan"
        >
          📤 Share
        </button>
      </div>

      <div className={styles.cardsGrid}>
        {plan.beforeMonsoon && plan.beforeMonsoon.length > 0 && (
          <div className={styles.card}>
            <h3 className={styles.cardTitle}>
              <span className={styles.cardIcon}>🛡️</span>
              Before Monsoon — Preparation Phase
            </h3>
            <ul className={styles.itemList}>
              {plan.beforeMonsoon.map((item, i) => (
                <li key={i} className={styles.listItem}>{item}</li>
              ))}
            </ul>
          </div>
        )}

        {plan.duringMonsoon && plan.duringMonsoon.length > 0 && (
          <div className={styles.card}>
            <h3 className={styles.cardTitle}>
              <span className={styles.cardIcon}>⛈️</span>
              During Monsoon — Active Safety
            </h3>
            <ul className={styles.itemList}>
              {plan.duringMonsoon.map((item, i) => (
                <li key={i} className={styles.listItem}>{item}</li>
              ))}
            </ul>
          </div>
        )}

        {plan.afterMonsoon && plan.afterMonsoon.length > 0 && (
          <div className={styles.card}>
            <h3 className={styles.cardTitle}>
              <span className={styles.cardIcon}>🌤️</span>
              After Monsoon — Recovery
            </h3>
            <ul className={styles.itemList}>
              {plan.afterMonsoon.map((item, i) => (
                <li key={i} className={styles.listItem}>{item}</li>
              ))}
            </ul>
          </div>
        )}

        {plan.emergencyChecklist && plan.emergencyChecklist.length > 0 && (
          <div className={styles.card}>
            <h3 className={styles.cardTitle}>
              <span className={styles.cardIcon}>✅</span>
              Emergency Checklist
            </h3>
            <div>
              {plan.emergencyChecklist.map((item, i) => (
                <ChecklistItem key={i} id={`emergency-${i}`} label={item} />
              ))}
            </div>
          </div>
        )}

        {plan.emergencyContacts && plan.emergencyContacts.length > 0 && (
          <div className={styles.card}>
            <h3 className={styles.cardTitle}>
              <span className={styles.cardIcon}>📞</span>
              Emergency Contacts
            </h3>
            <div className={styles.itemList}>
              {plan.emergencyContacts.map((contact, i) => (
                <div key={i} className={styles.contactItem}>
                  <span className={styles.contactName}>{contact.name}</span>
                  <span className={styles.contactNumber}>{contact.number}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {((plan.safetyDos && plan.safetyDos.length > 0) || (plan.safetyDonts && plan.safetyDonts.length > 0)) && (
          <div className={styles.card}>
            <h3 className={styles.cardTitle}>
              <span className={styles.cardIcon}>⚠️</span>
              Safety Do&apos;s and Don&apos;ts
            </h3>
            <div className={styles.dosContainer}>
              {plan.safetyDos && plan.safetyDos.length > 0 && (
                <div className={styles.dosColumn}>
                  <h3 className={styles.doTitle}>✅ Do&apos;s</h3>
                  {plan.safetyDos.map((item, i) => (
                    <div key={i} className={styles.doItem}>{item}</div>
                  ))}
                </div>
              )}
              {plan.safetyDonts && plan.safetyDonts.length > 0 && (
                <div className={styles.dosColumn}>
                  <h3 className={styles.dontTitle}>❌ Don&apos;ts</h3>
                  {plan.safetyDonts.map((item, i) => (
                    <div key={i} className={styles.dontItem}>{item}</div>
                  ))}
                </div>
              )}
            </div>
          </div>
        )}
      </div>

      {showToast && (
        <div className={styles.shareToast} role="status" aria-live="polite">
          ✅ Link copied to clipboard!
        </div>
      )}
    </section>
  );
}
